AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # SQS queue/DLQ for SHIP CONFIRM
  AfsSapShipConfirmDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: mp-ship-afssap-shipconfirm-dlq
      VisibilityTimeout: 300              # Visibility Timeout, 5 minutes
      MessageRetentionPeriod: 1209600     # Message Retention, 14 days
      ReceiveMessageWaitTimeSeconds: 0    # 0 seconds = short poll

  AfsSapShipConfirm:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: mp-ship-afssap-shipconfirm
      VisibilityTimeout: 300              # Visibility Timeout, 5 minutes
      MessageRetentionPeriod: 1209600     # Message Retention, 14 days
      ReceiveMessageWaitTimeSeconds: 0    # 0 seconds = short poll
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AfsSapShipConfirmDlq.Arn
        maxReceiveCount: 5