AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # SQS queue/DLQ for SHIP CANCEL
  AfsSapShipCancelDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: mp-ship-afssap-shipcancel-dlq
      VisibilityTimeout: 300              # Visibility Timeout, 5 minutes
      MessageRetentionPeriod: 1209600     # Message Retention, 14 days
      ReceiveMessageWaitTimeSeconds: 0    # 0 seconds = short poll

  AfsSapShipCancel:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: mp-ship-afssap-shipcancel
      VisibilityTimeout: 300              # Visibility Timeout, 5 minutes
      MessageRetentionPeriod: 1209600     # Message Retention, 14 days
      ReceiveMessageWaitTimeSeconds: 0    # 0 seconds = short poll
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AfsSapShipCancelDlq.Arn
        maxReceiveCount: 5